"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import "./automations.css";
type Automation={id:string;userId:string;name:string;prompt:string;schedule:{type:string;runAt?:string;hour?:number;minute?:number;minutes?:number};status:"active"|"paused"|"completed";nextRunAt?:string};
const userId="default-user";
export default function AutomationsPage(){
const [items,setItems]=useState<Automation[]>([]); const [name,setName]=useState(""); const [prompt,setPrompt]=useState(""); const [type,setType]=useState("once"); const [runAt,setRunAt]=useState(""); const [hour,setHour]=useState("9"); const [minute,setMinute]=useState("0"); const [interval,setIntervalMinutes]=useState("60"); const [busy,setBusy]=useState(false); const [status,setStatus]=useState("");
async function load(){const r=await fetch("/api/frosh/v1/automations/users/"+encodeURIComponent(userId),{cache:"no-store"});const d=await r.json();if(r.ok)setItems(d.automations??[]);else setStatus(d.error??"Unable to load automations.");}
useEffect(()=>{void load()},[]);
async function create(){setBusy(true);setStatus("");try{const schedule=type==="once"?{type,runAt:new Date(runAt).toISOString()}:type==="interval"?{type,minutes:Number(interval)}:{type,hour:Number(hour),minute:Number(minute)};const r=await fetch("/api/frosh/v1/automations/users/"+encodeURIComponent(userId),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name,prompt,schedule})});const d=await r.json();if(!r.ok)throw new Error(d.error??"Creation failed");setName("");setPrompt("");setStatus("Automation created.");await load()}catch(e){setStatus(e instanceof Error?e.message:"Creation failed")}finally{setBusy(false)}}
async function toggle(item:Automation){const next=item.status==="active"?"paused":"active";const r=await fetch("/api/frosh/v1/automations/users/"+userId+"/"+item.id,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({status:next})});const d=await r.json();setStatus(d.automation?"Automation "+next+".":d.error??"Update failed.");await load()}
async function remove(item:Automation){if(!confirm("Delete "+item.name+"?"))return;const r=await fetch("/api/frosh/v1/automations/users/"+userId+"/"+item.id,{method:"DELETE"});setStatus(r.ok?"Automation deleted.":"Delete failed.");await load()}
return <main className="automation-page"><header className="automation-header"><div><Link href="/" className="back">← FROSH Command Center</Link><div className="eyebrow">FROSH / AUTOMATIONS</div><h1>Automation Center</h1><p>Schedule recurring work, reminders, and future FROSH actions.</p></div></header>{status&&<div className="automation-status">{status}</div>}<section className="automation-builder"><div className="eyebrow">NEW AUTOMATION</div><input value={name} onChange={e=>setName(e.target.value)} placeholder="Name, e.g. Morning brief"/><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="What should FROSH do when this runs?"/><div className="schedule-row"><select value={type} onChange={e=>setType(e.target.value)}><option value="once">One time</option><option value="daily">Daily</option><option value="interval">Every interval</option></select>{type==="once"?<input type="datetime-local" value={runAt} onChange={e=>setRunAt(e.target.value)}/>:type==="interval"?<input type="number" min="60" value={interval} onChange={e=>setIntervalMinutes(e.target.value)}/>:<><input type="number" min="0" max="23" value={hour} onChange={e=>setHour(e.target.value)}/><input type="number" min="0" max="59" value={minute} onChange={e=>setMinute(e.target.value)}/></>}</div><button className="create" disabled={busy||!name.trim()||!prompt.trim()||(type==="once"&&!runAt)} onClick={()=>void create()}>{busy?"Creating…":"Create automation"}</button></section><section className="automation-list">{items.map(item=><article className="automation-card" key={item.id}><div><h2>{item.name}</h2><p>{item.prompt}</p></div><span className={"automation-state "+item.status}>{item.status}</span><div className="automation-meta">{item.nextRunAt?"Next: "+new Date(item.nextRunAt).toLocaleString():"No next run"}</div><div className="automation-actions"><button onClick={()=>void toggle(item)} disabled={item.status==="completed"}>{item.status==="active"?"Pause":"Resume"}</button><button onClick={()=>void remove(item)}>Delete</button></div></article>)}{!items.length&&<div className="automation-empty">No automations yet.</div>}</section></main>}
}