"use client";
import Link from "next/link"; import {useEffect,useState} from "react"; import "./missions.css";
type Mission={id:string;goal:string;status:string;progress:number;steps:Array<{title:string;status:string;result?:string}>;pendingApprovalId?:string;result?:string;createdAt:string};
const userId="default-user";
export default function MissionsPage(){const [items,setItems]=useState<Mission[]>([]);const [goal,setGoal]=useState("");const [status,setStatus]=useState("");
async function load(){const r=await fetch("/api/frosh/v1/missions/users/"+userId,{cache:"no-store"});const d=await r.json();if(r.ok)setItems(d.missions??[]);}
useEffect(()=>{void load()},[]);
async function create(){if(!goal.trim())return;const r=await fetch("/api/frosh/v1/missions/users/"+userId,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({goal})});const d=await r.json();if(r.ok){setGoal("");setStatus("Mission created.");await load()}else setStatus(d.error??"Could not create mission.")}
async function run(id:string){setStatus("FROSH is working on the next mission step…");const r=await fetch("/api/frosh/v1/missions/users/"+userId+"/"+id,{method:"POST"});const d=await r.json();setStatus(r.ok?"Mission step started.":d.error??"Mission failed.");await load()}\nasync function cont(id:string){setStatus("Continuing mission…");const r=await fetch("/api/frosh/v1/missions/users/"+userId+"/"+id+"/continue",{method:"POST"});const d=await r.json();setStatus(r.ok?"Mission continued.":d.error??"Mission continuation failed.");await load()}
async function remove(id:string){if(!confirm("Delete this mission?"))return;await fetch("/api/frosh/v1/missions/users/"+userId+"/"+id,{method:"DELETE"});await load()}
return <main className="missions-page"><header><Link href="/" className="back">← FROSH Command Center</Link><div className="eyebrow">FROSH / MISSIONS</div><h1>Autonomous Missions</h1><p>Give FROSH an objective. It can execute through the existing tool and approval system.</p></header>{status&&<div className="mission-status">{status}</div>}<section className="mission-create"><textarea value={goal} onChange={e=>setGoal(e.target.value)} placeholder="Example: Audit my website performance and tell me what needs fixing."/><button onClick={()=>void create()} disabled={!goal.trim()}>Create mission</button></section><section className="mission-list">{items.map(item=><article className="mission-card" key={item.id}><div className="mission-head"><span className={"mission-state "+item.status}>{item.status.replace("_"," ")}</span><span>{Math.round(item.progress*100)}%</span></div><h2>{item.goal}</h2><div className="progress"><i style={{width:(item.progress*100)+"%"}}/></div>{item.steps.map((step,index)=><div className="mission-step" key={index}><span className={step.status}>●</span><div><strong>{step.title}</strong><small>{step.status}</small>{step.result&&<p>{step.result}</p>}</div></div>)}{item.pendingApprovalId&&<div className="approval-note">Waiting for your approval before continuing.</div>}<div className="mission-actions"><button onClick={()=>void run(item.id)} disabled={item.status==="waiting_approval"||item.status==="completed"}>{item.status==="waiting_approval"?"Waiting for approval":"Run next step"}</button>{item.status==="waiting_approval"&&<button onClick={()=>void cont(item.id)}>Approve & Continue</button><button onClick={()=>void remove(item.id)}>Delete</button></div></article>)}{!items.length&&<div className="mission-empty">No missions yet.</div>}</section></main>}
}