"use client";
import Link from "next/link"; import {useEffect,useState} from "react"; import "./missions.css";
type Mission={id:string;goal:string;status:string;progress:number;steps:Array<{id?:string;title:string;status:string;result?:string}>;pendingApprovalId?:string;result?:string;createdAt:string};
type Event={id:string;type:string;message:string;stepId?:string;runId?:string;metadata?:Record<string,unknown>;createdAt:string};
const userId="default-user";
export default function MissionsPage(){const [items,setItems]=useState<Mission[]>([]);const [goal,setGoal]=useState("");const [status,setStatus]=useState(""); const [events,setEvents]=useState<Record<string,Event[]>>({});
async function load(){const r=await fetch("/api/frosh/v1/missions/users/"+userId,{cache:"no-store"});const d=await r.json();if(r.ok){const missions=d.missions??[];setItems(missions);const pairs=await Promise.all(missions.map(async(m:Mission)=>{const e=await fetch("/api/frosh/v1/missions/users/"+userId+"/"+m.id+"/events?limit=20",{cache:"no-store"});const x=await e.json();return [m.id,e.ok?(x.events??[]):[]] as const;}));setEvents(Object.fromEntries(pairs));}}
useEffect(()=>{void load();const timer=setInterval(()=>void load(),10000);return()=>clearInterval(timer)},[]);
useEffect(()=>{const active=items.filter(item=>item.status!=="completed"&&item.status!=="failed");const sources=active.map(item=>{const source=new EventSource("/api/frosh/v1/missions/users/"+userId+"/"+item.id+"/events/stream");source.onmessage=(message)=>{try{const event=JSON.parse(message.data) as Event;if(event.type==="heartbeat")return;setEvents(current=>({...current,[item.id]:[event,...(current[item.id]??[])].filter((entry,index,self)=>self.findIndex(x=>x.id===entry.id)===index).slice(0,20)}));}catch{}};return source});return()=>sources.forEach(source=>source.close())},[items]);
async function create(){if(!goal.trim())return;const r=await fetch("/api/frosh/v1/missions/users/"+userId,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({goal})});const d=await r.json();if(r.ok){setGoal("");setStatus("Mission created.");await load()}else setStatus(d.error??"Could not create mission.")}
async function run(id:string){setStatus("FROSH is working on the next mission step…");const r=await fetch("/api/frosh/v1/missions/users/"+userId+"/"+id,{method:"POST"});const d=await r.json();setStatus(r.ok?"Mission step started.":d.error??"Mission failed.");await load()}\nasync function cont(id:string){setStatus("Continuing mission…");const r=await fetch("/api/frosh/v1/missions/users/"+userId+"/"+id+"/continue",{method:"POST"});const d=await r.json();setStatus(r.ok?"Mission continued.":d.error??"Mission continuation failed.");await load()}
async function control(id:string,action:"pause"|"resume"|"cancel"){if(action==="cancel"&&!confirm("Cancel this mission?"))return;const r=await fetch("/api/frosh/v1/missions/users/"+userId+"/"+id+"/"+action,{method:"POST"});const d=await r.json();setStatus(r.ok?"Mission "+action+"d.":d.error??"Mission control failed.");await load()} async function remove(id:string){if(!confirm("Delete this mission?"))return;await fetch("/api/frosh/v1/missions/users/"+userId+"/"+id,{method:"DELETE"});await load()}
return <main className="missions-page"><header><Link href="/" className="back">← FROSH Command Center</Link><div className="eyebrow">FROSH / MISSIONS</div><h1>Autonomous Missions</h1><p>Give FROSH an objective. It can execute through the existing tool and approval system.</p></header>{status&&<div className="mission-status">{status}</div>}<section className="mission-create"><textarea value={goal} onChange={e=>setGoal(e.target.value)} placeholder="Example: Audit my website performance and tell me what needs fixing."/><button onClick={()=>void create()} disabled={!goal.trim()}>Create mission</button></section><section className="mission-list">{items.map(item=><article className="mission-card" key={item.id}><div className="mission-head"><span className={"mission-state "+item.status}>{item.status.replace("_"," ")}</span><span>{Math.round(item.progress*100)}%</span></div><h2>{item.goal}</h2><div className="progress"><i style={{width:(item.progress*100)+"%"}}/></div>{item.steps.map((step,index)=><div className="mission-step" key={index}><span className={step.status}>●</span><div><strong>{step.title}</strong><small>{step.status}</small>{step.result&&<p>{step.result}</p>}</div></div>)}{item.pendingApprovalId&&<div className="approval-note">Waiting for your approval before continuing.</div>}<div className="mission-events"><strong>Activity</strong>{(events[item.id]??[]).filter(event=>!event.type.startsWith("mission.tool.")).slice(0,8).map(event=><div className="mission-event" key={event.id}><span>{event.type.replace("mission.","").replaceAll("."," ")}</span><small>{new Date(event.createdAt).toLocaleString()}</small><p>{event.message}</p></div>)}</div><div className="mission-events mission-tools"><strong>Tool trace</strong>{(events[item.id]??[]).filter(event=>event.type.startsWith("mission.tool.")).slice(0,12).map(event=><div className="mission-event" key={event.id}><span>{String(event.metadata?.toolName??"tool")} · {event.type.endsWith("failed")?"failed":"completed"}</span><small>{String(event.metadata?.durationMs??"?")} ms · {new Date(event.createdAt).toLocaleTimeString()}</small><p>{event.message}</p></div>)}</div><div className="mission-actions"><button onClick={()=>void run(item.id)} disabled={item.status==="waiting_approval"||item.status==="completed"}>{item.status==="waiting_approval"?"Waiting for approval":"Run next step"}</button>{item.status==="waiting_approval"&&<button onClick={()=>void cont(item.id)}>Approve & Continue</button>}<button onClick={()=>void remove(item.id)}>Delete</button>{(item.status==="running"||item.status==="planning")&&<button onClick={()=>void control(item.id,"pause")}>Pause</button>}{item.status==="paused"&&<button onClick={()=>void control(item.id,"resume")}>Resume</button>}{!["completed","failed","cancelled"].includes(item.status)&&<button onClick={()=>void control(item.id,"cancel")}>Cancel</button>}</div></article>)}{!items.length&&<div className="mission-empty">No missions yet.</div>}</section></main>}
}